dist: artifacts
before:
   hooks:
     - go mod download
builds:
  - env:
    - CGO_ENABLED=0
    goos:
    - linux
    goarch:
    - amd64
    ignore:
    - goos: freebsd,darwin
      goarch: arm64,arm
    ldflags: -s -w -X main.version={{.Version}}
    binary: lynis_exporter