on:
  push:
    tags:
      - '*.*.*'

permissions:
    contents: write
    packages: write

name: Release 
jobs:
  goreleaser:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          goversion: "https://dl.google.com/go/go1.20.7.linux-amd64.tar.gz"
          binary_name: "lynis_exporter"

